//
//  ShowDetailsInterfaces.swift
//  TVShows
//
//  Created by Filip Gulan on 30/07/2018.
//  Copyright (c) 2018 Filip Gulan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

enum ShowDetailsNavigationOption {
}

protocol ShowDetailsWireframeInterface: WireframeInterface {
    func navigate(to option: ShowDetailsNavigationOption)
}

protocol ShowDetailsViewInterface: ViewInterface {
}

protocol ShowDetailsPresenterInterface: PresenterInterface {
    func setup(with output: ShowDetailsViewOutput) -> ShowDetailsViewInput
}

protocol ShowDetailsInteractorInterface: InteractorInterface {
}

struct ShowDetailsInput {
}

struct ShowDetailsViewInput {
}

struct ShowDetailsViewOutput {
}
