//
//  ShowDetailsViewController.swift
//  TVShows
//
//  Created by Filip Gulan on 30/07/2018.
//  Copyright (c) 2018 Filip Gulan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

final class ShowDetailsViewController: UIViewController {

    private let disposeBag = DisposeBag()

    // MARK: - Public properties -

    var presenter: ShowDetailsPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
    }
	
}

// MARK: - Extensions -

extension ShowDetailsViewController: ShowDetailsViewInterface {
}

private extension ShowDetailsViewController {

    func setupView() {
        let output = ShowDetailsViewOutput()
        _ = presenter.setup(with: output)
    }

}
