//
//  ShowDetailsInteractor.swift
//  TVShows
//
//  Created by Filip Gulan on 30/07/2018.
//  Copyright (c) 2018 Filip Gulan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Alamofire
import RxSwift

final class ShowDetailsInteractor {
    
    private let _service: Service
    private let _sessionManager: SessionManager
    
    init(showId: String, service: Service = .instance, sessionManager: SessionManager = ShowsSessionManager.session) {
        _service = service
        _sessionManager = sessionManager
    }
}

// MARK: - Extensions -

extension ShowDetailsInteractor: ShowDetailsInteractorInterface {
}
