//
//  LoginSInterfaces.swift
//  TVShows
//
//  Created by Filip Gulan on 29/07/2018.
//  Copyright (c) 2018 Filip Gulan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire

enum LoginSNavigationOption {
    case home
}

protocol LoginSWireframeInterface: WireframeInterface {
    func navigate(to option: LoginSNavigationOption)
}

protocol LoginSViewInterface: ViewInterface {
}

protocol LoginSPresenterInterface: PresenterInterface {
    func didSelectLoginWith(email: String, password: String)
    func didSelectRegisterWith(email: String, password: String)
}

protocol LoginSInteractorInterface: InteractorInterface {
    func login(email: String, password: String, completion: @escaping (Result<LoginData>) -> ())
    func register(email: String, password: String, completion: @escaping (Result<User>) -> ())
}
