//
//  LoginSWireframe.swift
//  TVShows
//
//  Created by Filip Gulan on 29/07/2018.
//  Copyright (c) 2018 Filip Gulan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class LoginSWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "LoginS", bundle: nil)

    // MARK: - Module setup -

    init() {
        let moduleViewController = _storyboard.instantiateViewController(ofType: LoginSViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = LoginSInteractor()
        let presenter = LoginSPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension LoginSWireframe: LoginSWireframeInterface {

    func navigate(to option: LoginSNavigationOption) {
        switch option {
        case .home:
            navigationController?.pushWireframe(HomeWireframe())
        }
    }
}
