//
//  LoginInteractor.swift
//  TVShows
//
//  Created by Filip Gulan on 29/07/2018.
//  Copyright (c) 2018 Filip Gulan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Alamofire
import RxSwift

final class LoginInteractor {
    
    private let _service: Service
    private let _sessionManager: SessionManager
    
    init(service: Service = .instance, sessionManager: SessionManager = ShowsSessionManager.session) {
        _service = service
        _sessionManager = sessionManager
    }
}

// MARK: - Extensions -

extension LoginInteractor: LoginInteractorInterface {
    
    func loginWith(email: String, password: String) -> Single<Void> {
        let service = _service
        let sessionManager = _sessionManager
        
        return Single.just(())
            .map { Router.User.loginWith(email: email, password: password) }
            .flatMap { service.request(LoginData.self, router: $0) }
            .do(onSuccess: { sessionManager.adapter = TokenAdapter(token: $0.token) })
            .mapToVoid()
    }
    
    func registerWith(email: String, password: String) -> Single<Void> {
        let service = _service
        
        return Single.just(())
            .map { Router.User.registerWith(email: email, password: password) }
            .flatMap { service.request(User.self, router: $0) }
            .mapToVoid()
    }
}
