//
//  HomeInterfaces.swift
//  TVShows
//
//  Created by Filip Gulan on 29/07/2018.
//  Copyright (c) 2018 Filip Gulan. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift
import RxCocoa

enum Home {
    
    struct ViewOutput {
        let refresh: Driver<Void>
        let logoutPressed: Driver<Void>
    }
    
    struct ViewInput {
        let items: Driver<[CollectionCellItem]>
    }
    
    enum NavigationOption {
        case showDetails(showId: String)
    }
}


protocol HomeWireframeInterface: WireframeInterface {
    func navigate(to option: Home.NavigationOption)
}

protocol HomeViewInterface: ViewInterface, Refreshable {
}

protocol HomePresenterInterface: PresenterInterface {
    func setup(with output: Home.ViewOutput) -> Home.ViewInput
}

protocol HomeInteractorInterface: InteractorInterface {
    
    func loadShows() -> Single<[Show]>
}
